### ISSUE TITLE
Check for Google Play services in main activity

### ISSUE THREAD

**Issue by arashpayan** [zood/george#3]

**Comment by IzzySoft** [comment]
Still there (or there again?).

Speaking of privacy: Your app comes with Google Mobile Services, Google Maps and Firebase. Google isn't exactly known as a privacy-focused company. At least Google Maps should not be too difficult to replace by e.g. OSM, eliminating one offender. Guess Firebase is there for FCM, which is harder to replace – but other projects (like Tutanota) managed even that; some options are [listed here](https://gitlab.com/snippets/1896503#push). GMS was most likely dragged in by Firebase, and thus should just be gone automatically then.

Would you mind?

**Comment by arashpayan** [comment]
hey @IzzySoft. I just opened a new issue that can be used to track the requirements and progress for F-Droid inclusion https://github.com/zood/george/issues/67

I believe that issue addresses all the points you've outlined.

**Comment by IzzySoft** [comment]
Thanks! Heading over there.
