### ISSUE TITLE
App is not working corretly on ungoogled phone (no Google Play Servicies)

### ISSUE THREAD

**Issue by greggkrishnan** [zood/george#71]
I have ungoogled phone (LineageOS) without google play services. Because of that map in app is not working.

It should be replaced with OpenStreetMaps so it works on all devices.

Edit: Probably loosely related to this issue: [Make app available via F-Droid #67](https://github.com/zood/george/issues/67)

**Comment by arashpayan** [comment]
As noted in your comment, this is covered in #67. That said, do you have migrog on your phone. I've heard from several folks that are successfully using the Zood with microg (no Google Play Services at all).
