### ISSUE TITLE
[ Serious Security Issue] Anyone track you just with username

### ISSUE THREAD

**Issue by pixincreate** [zood/george#72]
So, I just set-up the app for testing, and found out that, when you put the username to Add-Friend, it directly adds without even notifying/prompting the user on the other side which leads to easy tracking as the live location is shared instantly.
Add a user prompt so that the user who's location will be shared is notified and the one who wants to see the data has to request permission to get the location.

**Comment by arashpayan** [comment]
Hi @pixincreate.

It may be easier to illustrate this with some names. Let's suppose that Alice goes to the add a friend screen in Zood and adds Bob as a friend. At that point, Bob will see Alice show up as a friend on his phone. However, Bob's location will *not* be shared with Alice, unless Bob clicks on Alice and enables the toggle to share his location back to her.

I agree that it would be nice if there was a notification that asked Bob if he actually wanted to even see Alice as a friend on his list. But even right now without that notification, the worst thing that happens is that Bob starts seeing Alice's location (who explicitly shared it). Bob still has to explicitly opt in to sharing his location with Alice by clicking on her in the list of friends and then enabling the toggle.

I hope that helps clear it up. :slightly_smiling_face:

**Comment by pixincreate** [comment]
> I agree that it would be nice if there was a notification that asked Bob if he actually wanted to even see Alice as a friend on his list.


hoping implementation of this...

**Comment by arashpayan** [comment]
Just opened #73 to track this. :)
