### ISSUE TITLE
Location does not work on GrapheneOS

### ISSUE THREAD

**Issue by devrandom** [zood/george#74]
Platform: GrapheneOS with Google Play Services.

The following issues occur:

- a dialog appears "For a better experience, turn on device location, which uses Google's location service"
- regardless of what selection is made in the dialog, the location marker is not on the map
- clicking on the crosshairs icon (top-right), turns it blue, but otherwise there's no effect

**Comment by greenerk** [comment]
Chiming in here too on this one.  GrapheneOS, but no Google Play Services.
Just a black map after going through the sign-up process.
I'm installing the APK directly from GitHub.

A real shame as this is the **exact** tool I've been looking for - real-time, always-on sharing of location with a select few.  Just like Google Maps Location Sharing did for me.

I'm currently running a janky OwnTracks solution.  So I'd happily pay for this service (even better if there was a family plan) if it could run on GrapheneOS.

**Comment by nep2ner** [comment]
@greenerk Same, this app is _so close_ to what I've been looking out for.

Would you mind sharing how you set up your backend for OwnTracks? I never could get any back end working for that.

**Comment by greenerk** [comment]
> Would you mind sharing how you set up your backend for OwnTracks? I never could get any back end working for that.

Sure thing.

I followed [this guide on Reddit](https://www.reddit.com/r/selfhosted/comments/raade4/quick_owntracksrecorderindocker_dummies_guide/).  If you're familiar with Docker and Caddy you should be OK.  Be sure to check every line as some are just examples to be amended to suit your environment and some of the numbering is out of whack (appears to have been edited over time).

It's very fiddly, but works.  Me and my wife are able to check in on each other when needed via the OwnTracks Android app (also installed via GitHub APK).  And I even have an old android handset hidden in the car as a cheap tracker.

**Comment by arashpayan** [comment]
Hey all. Until the iOS app is released, this isn't something that I will be working on. Additionally, running a tile server that can replace Google Maps and the reverse geocoding will cost a non-trivial amount of money so there needs to be some revenue to pay for it.

This and other issues that prevent the app from being distributed via F-Droid are documented in issue #67.
