### ISSUE TITLE
Android X86 support

### ISSUE THREAD

**Issue by minax007** [zood/george#79]
Hi @arashpayan 

I have tried your app on several different Android builds and see that it is only running fine (except some smaller issues) on systems with Google Services Framework. 

On systems with MircoG it starts correctly but crashes almost any time when a selection of a person is made or when I click on the refresh button. 

I have also tried Android X86 on my PC but there it doesn't start at all. 

Immidiately after clicking on the app symbol it crashes. 

It seems that the app tries to start as you can see for a moment a black rectangular on the left part of the screen - but then it disappars again.

**Comment by arashpayan** [comment]
I just release v0.40 which has support for x86 processors. Give it a try and let me know how it goes.
