### ISSUE TITLE
State of the project - open source iOS 

### ISSUE THREAD

**Issue by ShalokShalom** [zood/george#82]
Hi 

I see the activity in this repo has gone down for a year. 

You write on the homepage, that the iOS version is receiving an UI overhaul. 

I cannot find an iOS version - is it open source now? 

Can we help? 

Thanks a lot 🎆 🥳

**Comment by JordanPlayz158** [comment]
I do hope development is continued (or the app is complete, not abandoned/unmaintained) as I would love to switch off of life360 but one of my family members (a single one) uses iOS, even if the iOS one is unfinished, it would be nice to have something out there, even if it doesn't look very good or is partially functioning

**Comment by ShalokShalom** [comment]
Well, if it would be open source, we all could contribute.

**Comment by ShalokShalom** [comment]
They allow Firefox, as an example. And their operating system itself is largely open as well. They are not that against open source - Swift, their language is, as an example - they just don't tout it from the rooftops.

**Comment by ShalokShalom** [comment]
They basically put largely closed source (Cocoa, XCode) on top of largely open source software (Mach kernel, freeBSD like userland) and there are also open source implementations of it. 

See: https://en.wikipedia.org/wiki/Darwin_(operating_system)
https://github.com/PureDarwin/PureDarwin

**Comment by arashpayan** [comment]
Hi all. I haven't abandoned development on the iOS app. Lately, I've been working on updating the Android app to accommodate some new requirements from the Google Play store (https://support.google.com/googleplay/android-developer/answer/11926878?hl=en).

The iOS app will be licensed under the terms of the AGPL3, but the code is not in a state where I could even consider receiving external contributions to it. Once it is, I'll make the repo public and also have a build available for people to try.

I know it's frustrating having to wait for an iOS client, especially when an Android client is already done, but I can only work on the project in my spare time.

If you would like me to email you when the iOS beta is ready, email me at `arash at zood dot xyz`.

**Comment by ShalokShalom** [comment]
I wish I would get a penny, every time someone believed their source code is not ready to get opened. ;)
