### ISSUE TITLE
ON/OFF app service switch

### ISSUE THREAD

**Issue by serrq** [zood/george#87]
I would like an on/off app service switch within the app and notification drawer to have the possibility to shutdown app service (no tracking) while GPS button is turned ON for other apps.

I can switch ON Zood app service and quickly got location service active according to my needs.

When app service is OFF, the app doesn't collect data, it doesn't ask for location data, it doesn't send data out. It's off, but it's ready to go if you select ON again.

**Comment by arashpayan** [comment]
I wouldn't want to complicate things for most users with something like this.
